name = "aimatchlab-ai-context-worker"
main = "src/index.ts"
compatibility_date = "2026-02-01"

[[r2_buckets]]
binding = "AIMATCHLAB_INTEL"
bucket_name = "aimatchlab-intel"

[[kv_namespaces]]
binding = "AIMATCHLAB_KV_CORE"
id = "3c7930b5401a4434bc7ecf28f677dee5"

[[kv_namespaces]]
binding = "AIMATCHLAB_STATS"
id = "830e99d5f21d4bb78a4ee13b4d04e842"
