name = "aimatchlab-details-worker"
main = "src/index.js"
compatibility_date = "2026-02-03"

kv_namespaces = [
  { binding = "AIMATCHLAB_DETAILS", id = "08c6e49ed0fd403aac6f1317549115ea" }
]

r2_buckets = [
  { binding = "AIML_ARCHIVE", bucket_name = "aimatchlab-leagues-archive" },
  { binding = "AIMATCHLAB_INTEL", bucket_name = "aimatchlab-intel" }
]
