name = "aimatchlab-standings-api-football"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = true

kv_namespaces = [
  { binding = "AIMATCHLAB_KV_CORE", id = "3c7930b5401a4434bc7ecf28f677dee5" }
]

[vars]
API_FOOTBALL_BASE = "https://v3.football.api-sports.io"
