name = "aimatchlab-absences-worker"
main = "index.js"
compatibility_date = "2026-02-04"

[vars]
DETAILS_BASE_URL = "https://aimatchlab-details-worker.pierros1402.workers.dev"

[[kv_namespaces]]
binding = "AIMATCHLAB_ABSENCES"
id = "867e97ce39fe42599bd62497cd66db23"

[[r2_buckets]]
binding = "AIML_ARCHIVE"
bucket_name = "aimatchlab-leagues-archive"
[[kv_namespaces]]
binding = "AIMATCHLAB_DETAILS"
id = "08c6e49ed0fd403aac6f1317549115ea"

