name = "aimatchlab-value-worker"
main = "aimatchlab-value-worker.js"
compatibility_date = "2026-01-01"
account_id = "3ae84689c002527bc182b870e4861ab4"

[[kv_namespaces]]
binding = "AIMATCHLAB_KV_CORE"
id = "3c7930b5401a4434bc7ecf28f677dee5"

[[kv_namespaces]]
binding = "AIMATCHLAB_STATS"
id = "830e99d5f21d4bb78a4ee13b4d04e842"
