name = "aimatchlab-standings-uefa"
main = "index.js"
compatibility_date = "2024-12-01"

kv_namespaces = [
  { binding = "AIMATCHLAB_KV_CORE", id = "3c7930b5401a4434bc7ecf28f677dee5" }
]

# NO CRON — manual only
