name = "aimatchlab-api"
main = "index.js"
compatibility_date = "2024-01-01"

# =========================
# KV NAMESPACES
# =========================

[[kv_namespaces]]
binding = "AIML_INGESTION_KV"
id = "a4173ef1d949403f9f1217e55ba275c3"

[[kv_namespaces]]
binding = "AIML_INTEL_KV"
id = "2caa69b5632b47e98560fcafe72760e3"

[[kv_namespaces]]
binding = "AIMATCHLAB_STATS"
id = "830e99d5f21d4bb78a4ee13b4d04e842"

[[kv_namespaces]]
binding = "AIML_DETAILS_CACHE"
id = "4bb3c7a4abfb4d3aa10ffce22cf533e8"

# =========================
# R2 BUCKETS
# =========================

[[r2_buckets]]
binding = "R2_INTEL"
bucket_name = "aimatchlab-intel"

[[r2_buckets]]
binding = "R2_ARCHIVE"
bucket_name = "aimatchlab-leagues-archive"

[[r2_buckets]]
binding = "AI_STATE"
bucket_name = "aimatchlab-ai-state"

[[r2_buckets]]
binding = "R2_ODDS"
bucket_name = "aimatchlab-odds"
# =========================
# ENV VARS
# =========================

[vars]
ODDS_REGION = "eu"
ADMIN_EXPORT_TOKEN = "1234"
