name = "aimatchlab-value-engine"
main = "value-engine.js"
compatibility_date = "2026-01-24"

kv_namespaces = [
  { binding = "AIMATCHLAB_STATS", id = "830e99d5f21d4bb78a4ee13b4d04e842" },
  { binding = "AIMATCHLAB_KV_CORE", id = "3c7930b5401a4434bc7ecf28f677dee5" }
]

[vars]
VALUE_ENGINE_BUILD = "VALUE_ENGINE_BUILD_2026-01-24_CLEAN_V1"
