name = "aimatchlab-standings-api-football"
main = "index.js"
compatibility_date = "2025-01-01"

[vars]
API_FOOTBALL_KEY = "5db5900cca843cc42b88f998bc96318e"

[[kv_namespaces]]
binding = "AIMATCHLAB_KV_CORE"
id = "3c7930b5401a4434bc7ecf28f677dee5"
