
name = "aimatchlab-value-engine"
main = "src/index.js"
compatibility_date = "2026-02-07"

[[kv_namespaces]]
binding = "AIML_INGESTION_KV"
id = "a4173ef1d949403f9f1217e55ba275c3"

[[kv_namespaces]]
binding = "AIMATCHLAB_STATS"
id = "830e99d5f21d4bb78a4ee13b4d04e842"

[[r2_buckets]]
binding = "AIMATCHLAB_INTEL"
bucket_name = "aimatchlab-intel"
